# Generated by Django 2.0.5 on 2018-07-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_files',
            field=models.CharField(default='hy', max_length=500),
            preserve_default=False,
        ),
    ]
